// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ai/context/v1/annotations.proto

package ai_context_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KnowledgeTopic groups related capabilities into a single knowledge file.
// Apply on enums or messages to assign them to a topic.
// All items sharing the same topic value are aggregated into one .md file.
type KnowledgeTopic struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Topic identifier — becomes the output filename (e.g. "forms" → forms.md).
	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	// Human-readable title used as the markdown heading.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Summary paragraph appended to the knowledge file's index entry.
	// Should contain keywords users might say so the AI discovers this topic.
	Summary string `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	// Optional JSON payload example included in the generated file.
	Example string `protobuf:"bytes,4,opt,name=example,proto3" json:"example,omitempty"`
	// Behavioral notes, usage rules, and wiring guidance for AI agents.
	// Rendered as a dedicated "Usage Notes" section in the generated file.
	// Use this for rules that aren't derivable from the schema alone
	// (e.g. "RADIO/CHECKBOX require options array", "composite steps wire via payload").
	UsageNotes    string `protobuf:"bytes,5,opt,name=usage_notes,json=usageNotes,proto3" json:"usage_notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgeTopic) Reset() {
	*x = KnowledgeTopic{}
	mi := &file_ai_context_v1_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeTopic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeTopic) ProtoMessage() {}

func (x *KnowledgeTopic) ProtoReflect() protoreflect.Message {
	mi := &file_ai_context_v1_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeTopic.ProtoReflect.Descriptor instead.
func (*KnowledgeTopic) Descriptor() ([]byte, []int) {
	return file_ai_context_v1_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *KnowledgeTopic) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *KnowledgeTopic) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *KnowledgeTopic) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *KnowledgeTopic) GetExample() string {
	if x != nil {
		return x.Example
	}
	return ""
}

func (x *KnowledgeTopic) GetUsageNotes() string {
	if x != nil {
		return x.UsageNotes
	}
	return ""
}

// EnumValueContext adds AI-facing metadata to individual enum values.
// The protoc plugin collects these to build the capability summary.
type EnumValueContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable name (e.g. "Rating" instead of "FORM_FIELD_TYPE_RATING").
	HumanName string `protobuf:"bytes,1,opt,name=human_name,json=humanName,proto3" json:"human_name,omitempty"`
	// Comma-separated common user queries that should match this value
	// (e.g. "star rating, score, NPS, satisfaction").
	CommonQueries string `protobuf:"bytes,2,opt,name=common_queries,json=commonQueries,proto3" json:"common_queries,omitempty"`
	// Override topic assignment. If empty, inherits from the parent enum's topic.
	Topic         string `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumValueContext) Reset() {
	*x = EnumValueContext{}
	mi := &file_ai_context_v1_annotations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumValueContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumValueContext) ProtoMessage() {}

func (x *EnumValueContext) ProtoReflect() protoreflect.Message {
	mi := &file_ai_context_v1_annotations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumValueContext.ProtoReflect.Descriptor instead.
func (*EnumValueContext) Descriptor() ([]byte, []int) {
	return file_ai_context_v1_annotations_proto_rawDescGZIP(), []int{1}
}

func (x *EnumValueContext) GetHumanName() string {
	if x != nil {
		return x.HumanName
	}
	return ""
}

func (x *EnumValueContext) GetCommonQueries() string {
	if x != nil {
		return x.CommonQueries
	}
	return ""
}

func (x *EnumValueContext) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

// FieldContext adds AI-facing metadata to individual message fields.
type FieldContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable description for this field.
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// Example value (included in generated payload documentation).
	Example       string `protobuf:"bytes,2,opt,name=example,proto3" json:"example,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldContext) Reset() {
	*x = FieldContext{}
	mi := &file_ai_context_v1_annotations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldContext) ProtoMessage() {}

func (x *FieldContext) ProtoReflect() protoreflect.Message {
	mi := &file_ai_context_v1_annotations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldContext.ProtoReflect.Descriptor instead.
func (*FieldContext) Descriptor() ([]byte, []int) {
	return file_ai_context_v1_annotations_proto_rawDescGZIP(), []int{2}
}

func (x *FieldContext) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FieldContext) GetExample() string {
	if x != nil {
		return x.Example
	}
	return ""
}

var file_ai_context_v1_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*KnowledgeTopic)(nil),
		Field:         52100,
		Name:          "ai.context.v1.enum_knowledge",
		Tag:           "bytes,52100,opt,name=enum_knowledge",
		Filename:      "ai/context/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*EnumValueContext)(nil),
		Field:         52101,
		Name:          "ai.context.v1.enum_value_context",
		Tag:           "bytes,52101,opt,name=enum_value_context",
		Filename:      "ai/context/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*KnowledgeTopic)(nil),
		Field:         52102,
		Name:          "ai.context.v1.message_knowledge",
		Tag:           "bytes,52102,opt,name=message_knowledge",
		Filename:      "ai/context/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldContext)(nil),
		Field:         52103,
		Name:          "ai.context.v1.field_context",
		Tag:           "bytes,52103,opt,name=field_context",
		Filename:      "ai/context/v1/annotations.proto",
	},
}

// Extension fields to descriptorpb.EnumOptions.
var (
	// optional ai.context.v1.KnowledgeTopic enum_knowledge = 52100;
	E_EnumKnowledge = &file_ai_context_v1_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional ai.context.v1.EnumValueContext enum_value_context = 52101;
	E_EnumValueContext = &file_ai_context_v1_annotations_proto_extTypes[1]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional ai.context.v1.KnowledgeTopic message_knowledge = 52102;
	E_MessageKnowledge = &file_ai_context_v1_annotations_proto_extTypes[2]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional ai.context.v1.FieldContext field_context = 52103;
	E_FieldContext = &file_ai_context_v1_annotations_proto_extTypes[3]
)

var File_ai_context_v1_annotations_proto protoreflect.FileDescriptor

const file_ai_context_v1_annotations_proto_rawDesc = "" +
	"\n" +
	"\x1fai/context/v1/annotations.proto\x12\rai.context.v1\x1a google/protobuf/descriptor.proto\"\x91\x01\n" +
	"\x0eKnowledgeTopic\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x18\n" +
	"\aexample\x18\x04 \x01(\tR\aexample\x12\x1f\n" +
	"\vusage_notes\x18\x05 \x01(\tR\n" +
	"usageNotes\"n\n" +
	"\x10EnumValueContext\x12\x1d\n" +
	"\n" +
	"human_name\x18\x01 \x01(\tR\thumanName\x12%\n" +
	"\x0ecommon_queries\x18\x02 \x01(\tR\rcommonQueries\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\"J\n" +
	"\fFieldContext\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x18\n" +
	"\aexample\x18\x02 \x01(\tR\aexample:d\n" +
	"\x0eenum_knowledge\x12\x1c.google.protobuf.EnumOptions\x18\x84\x97\x03 \x01(\v2\x1d.ai.context.v1.KnowledgeTopicR\renumKnowledge:r\n" +
	"\x12enum_value_context\x12!.google.protobuf.EnumValueOptions\x18\x85\x97\x03 \x01(\v2\x1f.ai.context.v1.EnumValueContextR\x10enumValueContext:m\n" +
	"\x11message_knowledge\x12\x1f.google.protobuf.MessageOptions\x18\x86\x97\x03 \x01(\v2\x1d.ai.context.v1.KnowledgeTopicR\x10messageKnowledge:a\n" +
	"\rfield_context\x12\x1d.google.protobuf.FieldOptions\x18\x87\x97\x03 \x01(\v2\x1b.ai.context.v1.FieldContextR\ffieldContextBHZFgithub.com/Loschcode/protoc-gen-ai-context/ai/context/v1;ai_context_v1b\x06proto3"

var (
	file_ai_context_v1_annotations_proto_rawDescOnce sync.Once
	file_ai_context_v1_annotations_proto_rawDescData []byte
)

func file_ai_context_v1_annotations_proto_rawDescGZIP() []byte {
	file_ai_context_v1_annotations_proto_rawDescOnce.Do(func() {
		file_ai_context_v1_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_context_v1_annotations_proto_rawDesc), len(file_ai_context_v1_annotations_proto_rawDesc)))
	})
	return file_ai_context_v1_annotations_proto_rawDescData
}

var file_ai_context_v1_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ai_context_v1_annotations_proto_goTypes = []any{
	(*KnowledgeTopic)(nil),                // 0: ai.context.v1.KnowledgeTopic
	(*EnumValueContext)(nil),              // 1: ai.context.v1.EnumValueContext
	(*FieldContext)(nil),                  // 2: ai.context.v1.FieldContext
	(*descriptorpb.EnumOptions)(nil),      // 3: google.protobuf.EnumOptions
	(*descriptorpb.EnumValueOptions)(nil), // 4: google.protobuf.EnumValueOptions
	(*descriptorpb.MessageOptions)(nil),   // 5: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),     // 6: google.protobuf.FieldOptions
}
var file_ai_context_v1_annotations_proto_depIdxs = []int32{
	3, // 0: ai.context.v1.enum_knowledge:extendee -> google.protobuf.EnumOptions
	4, // 1: ai.context.v1.enum_value_context:extendee -> google.protobuf.EnumValueOptions
	5, // 2: ai.context.v1.message_knowledge:extendee -> google.protobuf.MessageOptions
	6, // 3: ai.context.v1.field_context:extendee -> google.protobuf.FieldOptions
	0, // 4: ai.context.v1.enum_knowledge:type_name -> ai.context.v1.KnowledgeTopic
	1, // 5: ai.context.v1.enum_value_context:type_name -> ai.context.v1.EnumValueContext
	0, // 6: ai.context.v1.message_knowledge:type_name -> ai.context.v1.KnowledgeTopic
	2, // 7: ai.context.v1.field_context:type_name -> ai.context.v1.FieldContext
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	4, // [4:8] is the sub-list for extension type_name
	0, // [0:4] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ai_context_v1_annotations_proto_init() }
func file_ai_context_v1_annotations_proto_init() {
	if File_ai_context_v1_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_context_v1_annotations_proto_rawDesc), len(file_ai_context_v1_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_ai_context_v1_annotations_proto_goTypes,
		DependencyIndexes: file_ai_context_v1_annotations_proto_depIdxs,
		MessageInfos:      file_ai_context_v1_annotations_proto_msgTypes,
		ExtensionInfos:    file_ai_context_v1_annotations_proto_extTypes,
	}.Build()
	File_ai_context_v1_annotations_proto = out.File
	file_ai_context_v1_annotations_proto_goTypes = nil
	file_ai_context_v1_annotations_proto_depIdxs = nil
}
